import React, { useState, useCallback, useEffect, useRef } from 'react';
import type { FormState } from '../../types';
import { VoiceInput } from '../common/VoiceInput';
import { generateSceneSuggestions } from '../../services/api';

interface SceneBuilderProps {
  formState: FormState;
  setFormState: React.Dispatch<React.SetStateAction<FormState>>;
}

export const SceneBuilder: React.FC<SceneBuilderProps> = ({ formState, setFormState }) => {
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [isLoadingSuggestions, setIsLoadingSuggestions] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const productName = formState.productChoice.custom.name;
  const productDesc = formState.productChoice.custom.description;
  const productImage = formState.productChoice.custom.image_url;

  // Indicateur de contexte produit suffisant pour générer des suggestions
  const hasProductContext = productName.trim().length > 2 || productImage.length > 0;

  const doGenerateSuggestions = useCallback(async () => {
    if (!hasProductContext) return;
    setIsLoadingSuggestions(true);
    try {
      const results = await generateSceneSuggestions([
        {
          name: productName || 'Produit visuel',
          category: productDesc || 'campagne marketing local',
        },
      ]);
      setSuggestions(results.slice(0, 4));
      // Auto-sélectionner la première suggestion si le champ scène est vide
      if (!formState.customScenePrompt && results.length > 0) {
        setFormState((s) => ({ ...s, customScenePrompt: results[0] }));
      }
    } catch (e) {
      console.warn('Scene suggestions failed:', e);
      // Fallback contextuel basé sur le produit
      const name = productName || 'le produit';
      const fallbacks = [
        `Scène chaleureuse en famille découvrant ${name}, lumière dorée du soir, ambiance conviviale`,
        `Marché de quartier animé, ${name} mis en valeur sur un étal coloré, clients souriants`,
        `Pause déjeuner entre collègues dans un bureau lumineux, ${name} au centre de la table`,
        `Terrasse ensoleillée d'un café de quartier, ${name} présenté avec soin`,
      ];
      setSuggestions(fallbacks);
      if (!formState.customScenePrompt) {
        setFormState((s) => ({ ...s, customScenePrompt: fallbacks[0] }));
      }
    } finally {
      setIsLoadingSuggestions(false);
    }
  }, [productName, productDesc, hasProductContext, formState.customScenePrompt, setFormState]);

  // Auto-génération quand le produit change (debounce 1.5s)
  useEffect(() => {
    if (!hasProductContext) return;
    if (hasAutoGenerated && suggestions.length > 0) return; // Ne pas re-générer si déjà fait

    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      setHasAutoGenerated(true);
      doGenerateSuggestions();
    }, 1500);

    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [productName, productDesc, productImage, hasProductContext]);

  const selectSuggestion = (text: string) => {
    setFormState((s) => ({ ...s, customScenePrompt: text }));
  };

  const handleRegenerate = () => {
    setHasAutoGenerated(false);
    setSuggestions([]);
    doGenerateSuggestions();
  };

  return (
    <div className="card">
      <h3 className="section-title">2. Scène & Direction artistique</h3>

      {/* Status indicator */}
      {!hasProductContext && (
        <div className="flex items-center gap-2 py-2 px-3 bg-amber-50 rounded-lg mb-3">
          <svg className="w-3.5 h-3.5 text-amber-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4.5c-.77-.833-2.694-.833-3.464 0L3.34 16.5c-.77.833.192 2.5 1.732 2.5z" />
          </svg>
          <span className="text-xs text-amber-700">Renseignez un produit pour obtenir des suggestions de scènes adaptées.</span>
        </div>
      )}

      {/* Custom Scene Prompt */}
      <div className="flex gap-2 mb-3">
        <textarea
          value={formState.customScenePrompt}
          onChange={(e) => setFormState((s) => ({ ...s, customScenePrompt: e.target.value }))}
          placeholder={hasProductContext ? `Décrivez la scène idéale pour "${productName || 'votre produit'}"...` : 'Décrivez la scène idéale pour votre visuel...'}
          rows={3}
          className="input-field text-sm resize-none flex-1"
        />
        <div className="flex flex-col gap-1.5">
          <VoiceInput
            onTranscript={(t) =>
              setFormState((s) => ({
                ...s,
                customScenePrompt: (s.customScenePrompt + ' ' + t).trim(),
              }))
            }
          />
        </div>
      </div>

      {/* AI Suggestions button */}
      <button
        onClick={handleRegenerate}
        disabled={isLoadingSuggestions || !hasProductContext}
        className="w-full flex items-center justify-center gap-2 py-2 px-3 bg-purple-50 hover:bg-purple-100 text-purple-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-40 mb-2"
      >
        {isLoadingSuggestions ? (
          <>
            <svg className="animate-spin h-3.5 w-3.5" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            Analyse du produit et génération...
          </>
        ) : (
          <>
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            {suggestions.length > 0 ? 'Régénérer les propositions' : '4 propositions adaptées au produit'}
          </>
        )}
      </button>

      {/* Suggestions */}
      {suggestions.length > 0 && (
        <div className="space-y-1.5">
          {suggestions.map((s, i) => (
            <button
              key={i}
              onClick={() => selectSuggestion(s)}
              className={`w-full text-left px-3 py-2 rounded-lg text-xs transition-all duration-200 ${
                formState.customScenePrompt === s
                  ? 'bg-purple-50 border border-purple-200 text-purple-700'
                  : 'bg-gray-50 hover:bg-gray-100 text-gray-600'
              }`}
            >
              {s}
            </button>
          ))}
        </div>
      )}
    </div>
  );
};
